### ISSUE TITLE
Redis OM

### ISSUE THREAD

**Issue by ladderschool** [valkey-io/iovalkey#8]
I love the fork, great job! I was wondering if the Redis OM is something that could be supported? Someone tried to "patch" ioredis a few years back to support it:
https://github.com/redis/redis-om-node/issues/136

**Comment by mcollina** [comment]
Thanks for reporting!  My understanding is that Redis-OM relies on Redis JSON, which is not Open Source: https://github.com/RedisJSON/RedisJSON?tab=readme-ov-file#license.

My recommendation would be to open an issue on valley proper and discuss the implementation of this plugin.
